# Python [Numpy](https://numpy.org/) 
 NumPy is a Python library , which supports multi-dimensional arrays and matrices. In adition, Numpy supports a  collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

# Array creation

In [2]:
# Create array from a list
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Create from Array Range
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Create evenly spaced values within a given range
a = np.arange(1,21,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [5]:
# Create By specifying the number of elements
a = np.linspace(0, 1, 5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
#Create with Random-initialization
a = np.empty(3)
a

array([0., 0., 0.])

In [7]:
# Create with (One or Zero)-initialization

a = np.zeros(5)
print("All zeros array ", a)

b = np.ones((3,4))
b


All zeros array  [0. 0. 0. 0. 0.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#Create Diagonal Array
a = np.eye(3) # 3 x 3 , Diagonal array Initialized with ONEs (Identity/Unit)
print("Identity Matrix ", a)

b = np.diag([1,2,3,4]) # 4 x4 , Diagonal array Initialized with 1,2,3,4 respectivily
b

Identity Matrix  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Load NumPy Arrays From Text

In [9]:
# Import your data
x, y, z = np.loadtxt('data.txt',skiprows=1,unpack=True)
x

array([0.2536, 0.4839, 0.1292, 0.1781, 0.6253])

In [10]:
a = np.loadtxt('data.txt',skiprows=1,unpack=False)
a

array([[0.2536, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486, 0.8791]])

In [11]:
a = np.genfromtxt('data_missing.txt', skip_header=1)
a

array([[   nan, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292,    nan, 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486,    nan]])

In [12]:
a = np.genfromtxt('data_missing.txt', skip_header=1, filling_values=0)
a

array([[0.    , 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.    , 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486, 0.    ]])

# Save NumPy Arrays

In [13]:
np.savetxt('test.out', a, delimiter=',')

In [14]:
# Array lenght
a = np.arange(10)

print("Array Lenght ", len(a))

# Array Shape
print("Array Shape ", a.shape)

Array Lenght  10
Array Shape  (10,)


In [15]:
# Matrix length
a = np.ones((3,4))

print("Matrix Lenght ", len(a))

# Matrix Shape
print("Matrix Shape ", a.shape)

Matrix Lenght  3
Matrix Shape  (3, 4)


In [16]:
# Array Size: return number of elements
a = np.ones((3,4))

print("Array Size ", a.size)

Array Size  12


In [17]:
# Display Elements type
a = np.ones((3,4))
print("Default Data Type ",a.dtype)

# Define Elements Type
b = np.ones((3,4),dtype=np.float32)
print("Defined Data Type ",b.dtype)

Default Data Type  float64
Defined Data Type  float32


# Array Slicing & Reshaping

In [18]:
# Array Reshaping
a=np.arange(15) # Create Array “a” one row , 15 columns

b=a.reshape(3,5) # reshape to 3 rows , 5 columns
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# Array Slicing: we can constructe a slice by start:stop:step notation 

# All columns, first two rows
print("All columns, first two rows ", b[0:2,:])

# Third columns, first two rows
print("Third columns, first two rows ", b[0:2,2])


All columns, first two rows  [[0 1 2 3 4]
 [5 6 7 8 9]]
Third columns, first two rows  [2 7]


# [ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)
NumPy ufuncs are functions that operate element-wise on one or more arrays
- Arithmetic
    * + , - , * , / , square
- comparison operation
    * <, <=, == , != , >= , >
- Exponential operations
    * Exp2 Calculate 2**p for all p in the input array.
    * log Natural logarithm, element-wise.
    * log2 Base-2 logarithm of x.
    * log10 Return the base 10 logarithm of the input array, element-wise.
    * sqrt Return the non-negative square-root of an array, element-wise.
    * square Return the element-wise square of the input.
    * cbrt Return the cube-root of an array, element-wise.
    * power First array elements raised to powers from second array, element-wise.
    * Remainder Return element-wise remainder of division.
    * mod Return element-wise remainder of division.
    * fmod Return the element-wise remainder of division.
    * divmod Return element-wise quotient and remainder simultaneously.
    * absolute Calculate the absolute value element-wise.
    * fabs Compute the absolute values element-wise.

In [20]:
a = np.arange(5)
b = np.exp2(a)
c = np.log2(b)
print("a ", a)
print("b ", b)
print("c ", c)

a  [0 1 2 3 4]
b  [ 1.  2.  4.  8. 16.]
c  [0. 1. 2. 3. 4.]


# NumPy Broadcasting
Broadcasting is a mechanism that allows NumPy to work with arrays of different shapes when you’re performing arithmetic operations.

In [21]:
a = np.ones((3,4))
b = np.ones(4)
c = a + b
c

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [22]:
d = np.subtract(a,a) #multiply
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Axis Sum

In [23]:
a = np.arange(15)
a = a.reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
sum(a)

array([15, 18, 21, 24, 27])

In [25]:
np.sum(a)

105

In [26]:
a.sum(axis=0)

array([15, 18, 21, 24, 27])

In [27]:
a.sum(axis=0)

array([15, 18, 21, 24, 27])